FROM openjdk:8-jre

ENV KAFKA_VERSION=3.4.0
ENV SCALA_VERSION=2.13

RUN curl https://downloads.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz -o kafka.tgz \
    && tar -xzf kafka.tgz \
    && mv kafka_${SCALA_VERSION}-${KAFKA_VERSION} /kafka \
    && rm kafka.tgz

ENV PATH=${PATH}:/kafka/bin

CMD ["kafka-server-start.sh", "/kafka/config/server.properties"]
