version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - chatbot

  kafka:
    build: 
      context: .
      dockerfile: Dockerfile.kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "${KAFKA_TOPIC}:1:1"
    depends_on:
      - zookeeper
    networks:
      - chatbot

  chatbot:
    build: .
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - chatbot

networks:
  chatbot:
    driver: bridge
